### ISSUE TITLE
Psaní pošty nebo odpovědí - není vidět, co píšu při víc než asi 6 řádcích 

### ISSUE THREAD

**Issue by aditucz** [b3da-cz/rn-nyx-app#1]
Ve chvíli, kdy píšu post/odpověď/zprávu delší než pár řádků, přes klávesnici na obrazovce nevidím, co píšu. Nedá se napsaným textem scrollovat, nepomůže ani schovaní klávesnice.

**Comment by aditucz** [comment]
Android 7.1.2, telefon Xiaomi Redmi 4x global. U větších displayů / rozlišení se možná nemusí projevit?

**Comment by b3da-cz** [comment]
melo by byt opraveno v 0.1.16 6c18f7c6649f9fb3f4d5759caa89d3d240330ee9
funguje?

**Comment by aditucz** [comment]
Ano, napsaným nebo pastovaným textem se ve verzi 0.1.16 už dá v message boxu hýbat nahoru / dolů.  Díky :)
