### ISSUE TITLE
Nefunguje hodnocení palečky 

### ISSUE THREAD

**Issue by aditucz** [b3da-cz/rn-nyx-app#6]
Ani pozitivní, ani negativní ve verzi 0.1.15. Ve verzi 0.1.14 tenhle problém nezaznamenán.

**Comment by aditucz** [comment]
Zobrazení už udělených palců u příspěvku funguje

**Comment by b3da-cz** [comment]
opraveno 6c18f7c6649f9fb3f4d5759caa89d3d240330ee9
