### ISSUE TITLE
Zobrazení obrázků malé velikosti v diskuzi 

### ISSUE THREAD

**Issue by aditucz** [b3da-cz/rn-nyx-app#8]
nyx.cz/discussion/95/id/53622943 - rozlišení obrázku 161×216, v Nnn roztažený v rámci diskuze přes celou obrazovku (takže už tak slabá kvalita se ještě zhorší), při otevření v galerii se vrátí na původní velikost. Buď bych obrátila logiku, nebo obrázky do velikosti rozlišení telefonu radši nezvětšovala vůbec. 

Verze 0.1.18, android 7.1.2, Xiaomi Redmi 4x global

**Comment by b3da-cz** [comment]
S timhle je trosku problem:
Pro zobrazeni seznamu prispevku potrebuju znat jejich rozmery pred vykreslenim. To je mj. nutnost pro odskakovani na prvni neprecteny, ale potreba je to i v jinych pripadech. Protoze Nyx posila rozmery obrazku z nejakeho duvodu jen na webu, musim zjistit jejich rozmery (pomery stran) pred tim, nez zobrazim diskuzi. To mohu delat z originalnich obrazku, nebo z nahledu ktere Nyx generuje..
Poptavani velikosti nahledu je daleko mene narocne na data a cas nez tahani celych obrazku, ale nedostanu realny rozmer - jen rozmer nahledu, ze ktereho spocitam pomer stran komponenty do ktere po zobrazeni klubu a doscrolovani k zobrazene oblasti dotahuji original.
Kdybych tyhle rozmery pouzil natvrdo pro obrazky mensi nez sirka displeje, v podstate vsechny obrazky v tele prispevku by se zmensily na rozmer nahledu.. 
I kdyz tohle reseni neni idealni a male procento obrazku, ktere jsou v originalu mensi nez displej se tim padem zobrazuje skalovane, aktualne nevidim hezke reseni
